### ISSUE TITLE
is the vignette properly formatted

### ISSUE THREAD

**Issue by vjcitn** [neurogenomics/MungeSumstats#1]
I think you need a space before your bulletted list in markdown -- this is what i see upon rendering via install.packages build_vignettes=TRUE

<img width="788" alt="Screen Shot 2021-04-28 at 11 43 15 AM" src="https://user-images.githubusercontent.com/4624066/116438596-98245280-a81c-11eb-899c-468a9b905b53.png">

**Comment by Al-Murphy** [comment]
Yep, can't believe I missed that! Thank you very much, I'll push a change!
