### ISSUE TITLE
Update `compute_nsize` docs

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MungeSumstats#101]
The description of options for `compute_nsize(compute_n=)` is outdated ("effective" -> "ldsc", "giant", "metal", "sum"). Will update next time I make a push

 https://github.com/neurogenomics/MungeSumstats/blob/fb9ffb681d2e85e7ebdb13ccfb67aab976a6c431/R/compute_nsize.R#L25

**Comment by Al-Murphy** [comment]
Implemented
