### ISSUE TITLE
GenomicRanges style update broken for X chromosome

### ISSUE THREAD

**Issue by quattro** [neurogenomics/MungeSumstats#103]
Hi all,

Thanks for the super cool tool. It's made my life a lot easier. I ran into a bug recently that took some internal messing around to figure out what was going on during `liftover` from GRCh37->GRCh38. 

Internally the code pushes all `CHR` to lowercase (see [here](https://github.com/neurogenomics/MungeSumstats/blob/7feb5d53891f4404744c5f498f89968eb04c5ed6/R/check_no_snp.R#L78)), which in turn breaks the style requirements for `UCSC`.  It would be great to have this updated to work for all chromosome data, and not just autosomes.

Perhaps instead of a blanket `tolower` call maybe use a `gsub` that explicitly replaces any `'chr'` instance (regardless of case) with `'chr'`.

```
        rsids[, CHR := gsub("CHR", "chr", as.character(CHR), ignore.case=TRUE)]
        sumstats_dt[, CHR := gsub("CHR", "chr", as.character(CHR), ignore.case=TRUE)]
```

Cheers,
Nick

**Comment by Al-Murphy** [comment]
Hey,

Great to hear that you find the package useful! Happy to implement a change on this, just to confirm is the issue that sex chromosomes are being pushed to lower chase e.g. X -> x. I believe you are right and that UCSC uses 'X' rather than 'x'.

Let me know if this is what you mean and I'll push a fix.

Cheers.

**Comment by quattro** [comment]
Hi @Al-Murphy , yes that's correct. I tested out my above suggestion and it appears to fix the issue for now.

**Comment by Al-Murphy** [comment]
Fix pushed to RELEASE_3_15 and will be available in Bioconductor in the next few days

**Comment by quattro** [comment]
Fantastic, thanks so much.
