### ISSUE TITLE
how to calculate EAF from FRQ_A and FRQ_U？

### ISSUE THREAD

**Issue by showers14** [neurogenomics/MungeSumstats#105]
**Is your feature request related to a problem? Please describe.**

Hello,

When I downloaded the GWAS summary statistic data, the only information I received was CHROM	ID	POS	A1	A2	FCAS	FCON	IMPINFO	BETA	SE	PVAL	NGT	DIRE	NCAS	NCON	NEFF. 

how to calculate EAF with these information？

**Describe the solution you'd like**
no

**Describe alternatives you've considered**
no

**Additional context**
thank you for your time

**Comment by Al-Murphy** [comment]
Closing down to inactivity. Feel free to reopen if you have more information
