### ISSUE TITLE
Allow users to supply the file in-memory

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MungeSumstats#11]
Would be nice to have an option to provide a table in R rather than the file path, as an alternative

**Comment by Al-Murphy** [comment]
This has now been implemented, summary statistics can be read directly as data frame or data table objects. This change will propagate to Bioconductor in the next release (3.14) which will happen in Sep/Oct. Until then you can get the latest version of MungeSumstats from github `install_github("neurogenomics/Mungesumstats")` or by installing the dev version of bioconductor where is also available `BiocManager::install(version = "devel")`.
