### ISSUE TITLE
validate_parameters checks for incorrect version of dbSNP package

### ISSUE THREAD

**Issue by ilevantis** [neurogenomics/MungeSumstats#114]
## 1. Bug description

With `SNPlocs.Hsapiens.dbSNP155.GRCh37` installed the following error is given when using `format_sumstats()` with `ref_genome=NULL` and `dbSNP=155`:

```
  Error in validate_parameters(path = path, ref_genome = ref_genome, convert_ref_genome = convert_ref_genome,  : 
    Install 'SNPlocs.Hsapiens.dbSNP155.GRCh37' to use 'GRCh37' as 'ref_genome' and 155 as dbSNP version
  Calls: <Anonymous> -> validate_parameters
```
This appears to be result of the following code incorrectly checking for `SNPlocs.Hsapiens.dbSNP144.GRCh37`:

https://github.com/neurogenomics/MungeSumstats/blob/master/R/validate_parameters.R#L170-L186

**Comment by Al-Murphy** [comment]
Ah silly mistake, thanks for catching this! 

Updated in v1.5.9

Thanks,
Alan.
