### ISSUE TITLE
Is function "liftover" available in R package?

### ISSUE THREAD

**Issue by RuochengDong** [neurogenomics/MungeSumstats#118]
## 1. Bug description

I was able to find the function "liftover" in the vignette but could not use it in R after I installed and libraryed the packages.

### Console output 

```
> library(MungeSumstats)
> gwas_to_hg38 <- liftover(sumstats_dt = gwas_format, 
+                                         ref_genome = "hg19", convert_ref_genome = "hg38")
Error in liftover(sumstats_dt = gwas_format, ref_genome = "hg19", convert_ref_genome = "hg38") : 
  could not find function "liftover"
> gwas_to_hg38 <- MungeSumstats::liftover(sumstats_dt = gwas_format, 
+                                         ref_genome = "hg19", convert_ref_genome = "hg38")
Error: 'liftover' is not an exported object from 'namespace:MungeSumstats'
```

In the help page, there is no function "liftover".
![image](https://user-images.githubusercontent.com/11526068/186284043-80185058-af15-4e89-9bdf-c93a1b527019.png)

### Expected behaviour   

I expect R to find this function and it will work.

**Comment by Al-Murphy** [comment]
It is available! 

```
> ?MungeSumstats::liftover()
ℹ Rendering development documentation for "MungeSumstats::liftover"
```
Perhaps you are using an old version of MSS? I'd advise installing at least the latest release version of MSS to use it (v1.4.5) as there have been numerous updates to it from past releases

**Comment by Al-Murphy** [comment]
Closing for now but feel free to reopen if you are still unable to use it
