### ISSUE TITLE
`compute_nsize`: handle a vector of sample sizes

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MungeSumstats#125]
Allow users to provide a numeric vector of sample sizes, so long as it exactly matches the number of rows in the data. Currently, when a numeric vector is provided, the same message gets repeated (one message/item in vector).

![Screenshot 2022-09-20 at 14 35 25](https://user-images.githubusercontent.com/34280215/191272210-cc69a018-a0ab-43dc-9506-8caa219f79e0.png)

This originally came up in `echodata::get_sample_size`. 
https://github.com/RajLabMSSM/echolocatoR/issues/114

**Comment by Al-Murphy** [comment]
This will be a bit more work than it might seen given the filtering steps that happen in MSS - it would be hard to know how many rows there are. It might be easier to have an input of the RS ID and the size but then it might just be easier to create the N column before passing to MSS

**Comment by bschilder** [comment]
Ah, good point.  Ok, summarising some options on how to proceed here:

1. When`length(compute)>1`, `compute_n` must be a named vector with RSID for each sample size.

Possible solution, but requires users to know the exact RSIDS, which may not be the same after RSID standardization, making mismatches likely. 

2. When`length(compute)>1`, throw an error and instruct users to supply only 1 element, or to add N pre-munging.

I think this makes the most sense atm. I'll make a mod and push if that's ok.

4. Moved `compute_nsize` further up in the `format_sumtats` function so that it gets run before any filtering has been done.

Also a possibility, but potentially introduces complications with other munging steps.

**Comment by Al-Murphy** [comment]
Fixed with option 2 in version 1.5.14
