### ISSUE TITLE
Clarity needed for the treatment of sex chromosomes 

### ISSUE THREAD

**Issue by LeiSunUofT** [neurogenomics/MungeSumstats#130]
Not sure if this is an issue: Enjoyed reading your recent Bioinformatics paper. One thing not clear to me is the treatment of the sex chromosomes, as 

In the text: "whether to remove mitochondrial SNPs or SNPs on the X or Y chromosome (see Table 1)."

But in Table 1 #27 check: "If any are found these are removed."

So, users do have an option of keeping the X and Y chromosomes? Any other special treatment of the sex chromosomes by MungeSumstats? 

Thank you.

**Comment by Al-Murphy** [comment]
Hey! Yes, by default X,Y and mitochondrial SNPs are removed but this can be changed by the user with the `rmv_chr` parameter in `format_sumstats`. The rest of the checks should run as normal even with this change and there should be any other special treatment (that I am aware of). Do let me know if you do find any issues though, in my experience it is less common that people will run MSS with these included so it may not be as extensively tested.

**Comment by LeiSunUofT** [comment]
Thank you very much for the clarification, Alan. Indeed, the sex chromosomes continued to be omitted. Intuitively, there should be more checks though, but I do not have a precise recommendation now. Currently, we are working on a 10-year follow-up commentary paper on the current status of the analysis and reporting of the sex chromosomes, and if you prefer we can contact you again as we gain clarity.  Finally, these two papers might be of interest to you: (on X chromsome data quality) https://pubmed.ncbi.nlm.nih.gov/35639794/ and (on how to deal with X-inactivation) https://pubmed.ncbi.nlm.nih.gov/34224641/

**Comment by Al-Murphy** [comment]
That would be great if you could keep me in the loop, thanks! Thank you for sharing those links too (email if that's easier - a.murphy@imperial.ac.uk).
