### ISSUE TITLE
could not find function "liftover"

### ISSUE THREAD

**Issue by ElizavetaElgaeva** [neurogenomics/MungeSumstats#136]
## 1. Bug description

(A clear and concise description of what the bug is.)

### Console output 

```
# Paste console output here (e.g. from R/python/command line)

```

### Expected behaviour   

(A clear and concise description of what you expected to happen.)

### Code 

(Please add the steps to reproduce the bug here. See [here](https://www.r-bloggers.com/2020/10/how-to-make-a-reprex/) for an intro to making a reproducible example (i.e. reprex) and why they're important! __This will help us to help you much faster.__)

```R
# Paste example here

```

### Data

(If possible, upload a small sample of your data so that we can reproduce the bug on our end. If that's not possible, please at least include a screenshot of your data and other relevant details.)

## 3. Session info

(Add output of the R function `utils::sessionInfo()` below. This helps us assess version/OS conflicts which could be causing bugs.)

<details>

```
# Paste utils::sessionInfo() output 

```
</details>

**Comment by ElizavetaElgaeva** [comment]
Hi! I loaded the MungeSumstats library and tried to call the liftover function, but got an error message: Error in liftover( <...> )  :   could not find function "liftover". I tried to type ?liftover into console and got the full description of the function, but still I am disabled to use it. What is the problem with it?

**Comment by Al-Murphy** [comment]
Hey! I imagine this could be a version issue, it's best if you install R 4.2 and Bioconductor 3.16 to install MSS >=v1.6.0. There was a lot of improvements in this version over previous. Also liftover should be available in this version. You can use `utils::sessionInfo()` to check you rR/bioconductor/MSS version or alternatively do `packageVersion('MungeSumstats')`

**Comment by Al-Murphy** [comment]
Closing this for now but feel free to reopen if this did not resolve your issue
