### ISSUE TITLE
Unclear why SNPs are not chosen for validation

### ISSUE THREAD

**Issue by jksull** [neurogenomics/MungeSumstats#139]
Hi MSS devs,

Again, thank you for your continued efforts in developing this tool! I'm really not sure if this is a bug or feature, so I apologise in advance if I have labeled it incorrectly.

**Is your feature request related to a problem? Please describe.**

It is unclear to me why some percentage of SNPs are not included in `Validating RSIDs ..... using BSgenome::snpsById...`

I refer to the following log file (I have included what I think is relevant, but please let me know if it would be useful to provide the full log):

```
Standardising column headers.
First line of summary statistics file:
chr	POS	ALT	REF	ES	SE	AF	P
Summary statistics report:
   - 12,216,219 rows
   - 13,930 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Checking for multi-GWAS.
Checking for multiple RSIDs on one row.
Checking for merged allele column.
Checking A1 is uppercase
Checking A2 is uppercase
Loading SNPlocs data.
There is no SNP column found within the data. It must be inferred from other column information.
Found  Indels. These won't be checked against the reference genome as it does not contain Indels.
WARNING If your sumstat doesn't contain Indels, set the indel param to FALSE & rerun MungeSumstats::format_sumstats()
Ensuring all SNPs are on the reference genome.
Loading SNPlocs data.
Loading reference genome data.
Preprocessing RSIDs.
Validating RSIDs of 10,861,649 SNPs using BSgenome::snpsById...
BSgenome::snpsById done in 51 seconds.
21,663 SNPs are not on the reference genome. These will be corrected from the reference genome.
Loading SNPlocs data.
Loading SNPlocs data.
Loading reference genome data.
Preprocessing RSIDs.
Validating RSIDs of 10,861,649 SNPs using BSgenome::snpsById...
BSgenome::snpsById done in 65 seconds.
Checking for correct direction of A1 (reference) and A2 (alternative allele).
There are 3,388 SNPs where A1 doesn't match the reference genome.
These will be flipped with their effect columns.

...
Checking for bi-allelic SNPs.
291,664 SNPs are non-biallelic. These will be removed.

...

Writing in tabular format ==> /workspace/<file>
Summary statistics report:
   - 10,569,985 rows (86.5% of original 12,216,219 rows)
   - 10,569,985 unique variants
   - 10,498 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Done munging in 8.064 minutes.
Successfully finished preparing sumstats file, preview:
Reading header.
```

Simply put, what happens to the (`12,216,219 original - [10,861,649 validated - 291,664 non bi-allelic] = `) 1,062,906 SNPs that are not validated, and are not written to the munged summary statistics?

I thought perhaps these were the number of rows that were identified to have indels in them, but when re-running MSS using `bi_allelic_filter = FALSE` the following happens:

1. I _keep_ the 291,664 non bi-allelic SNPs
2. But the resulting sumstats file appears to still have indels in them (see the second last and third last rows from a snippet of the munged sumstats below):

```
SNP      CHR     BP         A1   A2    BETA     SE   FRQ    P     IMPUTATION_SNP
rs10007607 4 44969521 G T -0.16947 0.072138 0.002642 0.0400000007987242 TRUE
rs10008281 4 100142302 C A -0.00129491 0.0049372 0.225925 0.940000100430209 TRUE
rs10008281 4 100142302 C T 0.0513048 0.0599194 0.001469 0.380000352953329 TRUE
rs10008317 4 131711224 C T -0.00267058 0.00989877 0.109287 0.889999986382576 TRUE
rs10008317 4 131711224 CTTATTTATTTAT C -0.00877363 0.00469256 0.346615 0.0739997069733888 TRUE
rs10009103 4 152197000 A ATTT 0.002914 0.0116521 0.0325582 0.749999545138786 TRUE
rs10009103 4 152197000 A T -0.000215308 0.00415118 0.521812 0.780000713574729 TRUE
```

The other consideration was that these are the not-unique variants, a thought that was motivated by looking at rows `36-57` of [load_ref_genome_data.R](https://github.com/neurogenomics/MungeSumstats/blob/021f36322101e8b5dbc796fd03a2fad3795f4dae/R/load_ref_genome_data.R).

However when I use the `unique()` method on my raw data, it actually only removes a handful of rows.

**Describe the solution you'd like**

More explicit logging with regards to what is being excluded from validation, and the reason for it.

**Additional context**

I am using MSS version `1.7.8`.

**Comment by Al-Murphy** [comment]
Hey! Thanks for the detailed issue.  

>what happens to the (12,216,219 original - [10,861,649 validated - 291,664 non bi-allelic] = ) 1,062,906 SNPs that are not validated, and are not written to the munged summary statistics

I believe there is a good reason why these are dropped and I am just missing a message to say when they are in fact dropped. One way to investigate this would be to rerun using the `log_folder` and `log_folder_ind` so that files are saved with any removed SNPs at the point they are removed. See the documentation for more:
```
#' @param log_folder_ind Binary Should log files be stored containing all
#' filtered out SNPs (separate file per filter). The data is outputted in the
#' same format specified for the resulting sumstats file. The only exception to
#' this rule is if output is vcf, then log file saved as .tsv.gz. Default is
#' FALSE.
#' @param log_folder Filepath to the directory for the log files and the log of
#' MungeSumstats messages to be stored. Default is a temporary directory. Note 
#' the name of the log files (log messages and log outputs) are now the same as 
#' the name of the file specified in the save path parameter with the extension 
#' '_log_msg.txt' and '_log_output.txt' respectively.
```
From this you should be able to see where they are dropped and if you let me know the filtering step I can add the necessary log message.

>I thought perhaps these were the number of rows that were identified to have indels in them, but when re-running MSS using bi_allelic_filter = FALSE 

You may know this but it is important to note there is a difference between bi-allelic SNPs (only one alt allele) and an indels (multiple base-pairs in the ref or alt). MSS will force the removal of indels in certain situations but will give a big warning message like this from where it checks if SNPs are on a reference genome:

```
Found X Indels. These won't be checked against the reference genome as it does not contain Indels.
WARNING If your sumstat doesn't contain Indels, set the indel param to FALSE & rerun MungeSumstats::format_sumstats()
```

**Comment by jksull** [comment]
> You may know this but it is important to note there is a difference between bi-allelic SNPs (only one alt allele) and an indels (multiple base-pairs in the ref or alt).

Thanks for pointing this out. This was known to me, but it makes me realise that these indels that were removed when `bi_allelic_filter = TRUE`, were therefore only removed because they were _also_ considered as non-biallelic SNPs.  

I am curious however: 

> MSS will force the removal of indels in certain situations 

What situations may these be?  I have tried to be thorough with reading the docs, but I may have missed this! It has come to my attention that indels may need to be handled a bit differently than they are currently. 

It may be better to create a new issue for this but I believe that both issues relate to handling indels and after some further investigation I realise that the issue is something a bit more complicated, so I will continue for now.

Imagine the following (real) situation which is affecting the dataset that this issue relates to:

**We have a raw dataset that contains the following variants**
```
chr	POS	ALT	REF	ES	SE	AF	P
8	134625772	GCCGAAGGAGA	G	9.74121e-4	0.00753359	0.081771	0.86000009654862275
8	134625772	A	G	0.0032263	0.0115306	0.039537	0.9899999895196127
8	134625772	GCCGAAGGAGA	G	6.41437e-4	0.00763662	0.080264	0.8200000899052511
```

When MSS infers the rsID, all three variants get assigned to `rs539065912` ([on dbSNP](https://www.ncbi.nlm.nih.gov/snp/?term=rs539065912) based on `chr` and `POS`.  Then the first variant is kept and the other two are dropped as duplicates.  Therefore the resulting munged file has only the variant:

```
SNP CHR    BP A1 A2        BETA         SE      FRQ         P 
rs539065912	8	134625772	G	GCCGAAGGAGA	-0.00011248	0.00725512	0.081771	0.840000026958711 
```

First and foremost, the decision to choose the first _duplicated_ variant is not ideal in that most downstream analysis would likely use single variants rather than indels.  For this situation in isolation, it would be good to check if any duplicated variants are indels, and if so, keep only (if any) the non-indel SNP.  If they are only indels, then I suppose it's okay to keep the first.  I think it may not be a bad idea to have a flag that removes any and all indels, or to have some additional control over how to deal with indels - accompanied by explicit logs about where, when, and why indels are removed?

However, to make matters worse, the SNPs that relate to the two indels (first and third row) in actual fact belong to an [entirely different rsID](https://www.ncbi.nlm.nih.gov/snp/?term=rs113855465) `rs113855465`, which means that the decision to infer the `rsID` of all three variants based on `CHR` and `BP` ultimately _dirties_ the resulting dataset.  This is dangerous as without taking a very meticulous approach in validating the resulting munged data, it would not have come to my attention.  In the above case, there is no situation where we would want to keep the indel SNP over the single-allele SNP, and we certainly wouldn't want to (incorrectly) infer the `rsID` of the indel to be that of the single-allele SNP.

To provide some additional context, the true _raw_ dataset that I used for this situation is a `VCF` file downloaded from https://gwas.mrcieu.ac.uk/ - specifically [this file](https://gwas.mrcieu.ac.uk/datasets/met-d-L_VLDL_P/).  The data in this format actually has `rsID`'s for most of the variants already, which is how I know that the indels in the above example have their own `rsID` of `rs113855465`.

**The variants as they appear in the VCF:**

```
8	134625772	rs113855465	G	GCCGAAGGAGA	.	PASS	AF=0.081771	ES:SE:LP:AF:ID	-0.00011248:0.00725512:0.0757207:0.081771:rs113855465
8	134625772	rs539065912	G	A	.	PASS	AF=0.039537	ES:SE:LP:AF:ID	-0.0066072:0.0111044:0.30103:0.039537:rs539065912
8	134625772	rs113855465	G	GCCGAAGGAGA	.	PASS	AF=0.080264	ES:SE:LP:AF:ID	-0.000295391:0.00735434:0.091515:0.080264:rs11385
```

The raw dataset has almost 600,000 rows with `rsID` missing.  So the way I was hoping to deal with this was to read in the vcf file using `readr::read_tsv()`, manually impute the `P` values as MSS expects (as it doesn't calculate P-values if -logP exists instead), and remove the `ID` column so that ALL of the variants have their `rsID`'s inferred using MSS.  The resulting `data frame` after reading in this VCF and before munging is the one that you can see in the first code block of this reply.

This evidently isn't the best approach, and I think is the source of this initial issue.  The problem is that if I read in the VCF file and do not remove the `ID` column where the rows with missing ID's have `NA` in the `ID` column from the data frame I was experiencing an error when writing the munged file.  Unfortunately I can't reproduce the error right now, and it may be the case that this error was my own doing rather than the munger (so the motivation for reading in the VCF and converting it to a dataframe may have been unnecessary to some extent), but my subsequent investigation has made me skeptical of munging with the NA's. 

That is, the SNPs (at least the dozen or so that I checked) that have `NA` values in the `ID` column pre-munging are missing entirely from any of the resulting log or munge files.  It is not clear where or why they are dropped.  I also don't think that they are internally removed in their entirety because the number of resulting unique variants written to the munged file are a bit more than when I would _manually_ remove all of these ~600,000 (591,593 to be exact) rows prior to munging (the results for which I describe in my [current solution](#current-solution). 

For reference, here is the code block I use to read in the `VCF` and then munge:

```
datasets <- tibble::tribble(
    ~data,  
      "met-d-L_VLDL_P",
      )
      
purrr::pwalk(datasets, function(data){
  raw <- readr::read_tsv(
      glue::glue("/nightingale_datasets/raw/", data, ".vcf"), 
      comment = "##", col_select = c('#CHROM', POS, ALT, REF, FORMAT, data)
      ) 
  raw_to_df <-raw%>%
    dplyr::rename(chr = '#CHROM') %>%
    tidyr::separate(
      data,
      sep = ":",
      into = raw %>%
        dplyr::filter(dplyr::row_number() == 1) %>%
        dplyr::pull(FORMAT) %>%
        stringr::str_split(":") %>%
        purrr::pluck(1),
      convert = TRUE
      ) %>%
      dplyr::mutate(P = 10^(-LP))%>%
      dplyr::select(., -c(FORMAT,LP))

      MungeSumstats::format_sumstats(raw_to_df,
                                    ref_genome = "GRCh37",
                                    dbSNP = 144,
                                    nThread = 6,
                                    force_new=TRUE,
                                    save_path = glue::glue("/workspace/TEST-WITH-FUNCTION/", data, ".munged.tsv"),
                                    log_mungesumstats_msgs= TRUE,
                                    allele_flip_check=TRUE,
                                    log_folder = "/workspace/TEST-WITH-FUNCTION",
                                    log_folder_ind=TRUE
                                    )
})
```

The log for the above run is :

```
Standardising column headers.
First line of summary statistics file:
chr	POS	ALT	REF	ES	SE	AF	ID	P
Summary statistics report:
   - 12,216,219 rows
   - 11,602,289 unique variants
   - 13,930 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Checking for multi-GWAS.
Checking for multiple RSIDs on one row.
Checking SNP RSIDs.
591,593 SNP IDs are not correctly formatted. These will be corrected from the reference genome.
Found  Indels. These won't be checked against the reference genome as it does not contain Indels.
WARNING If your sumstat doesn't contain Indels, set the indel param to FALSE & rerun MungeSumstats::format_sumstats()
Loading SNPlocs data.
Writing in tabular format ==> /workspace/TEST-WITH-FUNCTION/snp_not_found_from_chr_bp.tsv
...
Preprocessing RSIDs.
Validating RSIDs of 11,607,271 SNPs using BSgenome::snpsById...
BSgenome::snpsById done in 50 seconds.
Found 692,479 Indels. These won't be checked against the reference genome as it does not contain Indels.
...
There are 248 SNPs where neither A1 nor A2 match the reference genome. These will be removed.
Writing in tabular format ==> /workspace/TEST-WITH-FUNCTION/alleles_dont_match_ref_gen.tsv
There are 115 SNPs where A1 doesn't match the reference genome.
...
14,286 RSIDs are duplicated in the sumstats file. These duplicates will be removed
Writing in tabular format ==> /workspace/TEST-WITH-FUNCTION/dup_snp_id.tsv
...
Checking for bi-allelic SNPs.
291,723 SNPs are non-biallelic. These will be removed.
Writing in tabular format ==> /workspace/TEST-WITH-FUNCTION/snp_bi_allelic.tsv
...
1,620,588 SNPs (15.3%) have FRQ values > 0.5. Conventionally the FRQ column is intended to show the minor/effect allele frequency.
...
Writing in tabular format ==> /workspace/TEST-WITH-FUNCTION/met-d-L_VLDL_P.munged.tsv
Summary statistics report:
   - 10,569,471 rows (86.5% of original 12,216,219 rows)
   - 10,569,471 unique variants
   - 10,499 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Done munging in 7.155 minutes.
```

Now, if I try and find any of the following SNPs for which no `rsID` was available (but _was_ included in the input to MSS), they are nowhere to be found in any of the log outputs or the final munged file:

```
    chr    POS ALT       REF          ES      SE     AF ID        P
   <dbl>  <dbl> <chr>     <chr>     <dbl>   <dbl>  <dbl> <chr> <dbl>
 1     1  63735 CCTA      C      0.000792 0.00648 0.683  <NA>  0.800
 2     1 129010 AATG      A      0.00349  0.00609 0.427  <NA>  0.750
 3     1 251627 AC        A     -0.00158  0.00849 0.837  <NA>  0.900
 4     1 692794 CA        C      0.0118   0.00699 0.888  <NA>  0.160
 5     1 701779 GAATA     G      0.00726  0.0108  0.929  <NA>  0.460
 6     1 719854 CAG       C     -0.0148   0.0229  0.989  <NA>  0.350
 7     1 721104 TA        T     -0.0162   0.0161  0.969  <NA>  0.500
 8     1 722364 GATTT     G     -0.00812  0.0130  0.966  <NA>  0.550
 9     1 723753 AGAGAGAGG A     -0.00924  0.0131  0.966  <NA>  0.570
10     1 723798 CAG       C      0.0101   0.0152  0.0295 <NA>  0.570
11     1 724295 TGGAAC    T     -0.0213   0.0221  0.987  <NA>  0.220
12     1 724621 CAAATG    C     -0.00947  0.0124  0.964  <NA>  0.490
```

One thing I notice now while preparing this message, is that the log _does_ recognise the SNPs with `NA` values in the `ID` column (`591,593 SNP IDs are not correctly formatted. These will be corrected from the reference genome.`).  But I don't what happens with them. I also notice that the step where indels are flagged happens twice.  First it reports `Found  Indels. These won't be checked against the reference genome as it does not contain Indels.`, and then it reports `Found 692,479 Indels.`.  Curiously, when I turn the `allele_flip_check = FALSE` (keeping the rest of the above function identical_, this step is performed three times.  The first and third times it reports `Found  Indels` and the second it correctly reports `Found 692,479 Indels.`.  I'm really not sure what happens here, and considering the aforementioned problems with dealing with indels, I prefer to remove the `NA` rows from the input dataset completely.  Another issue that arises when setting `allele_flip_check = FALSE`, the number of variants output to `snp_bi_allelic.tsv` grows to 1,037,559. This contradicts the immediately preceding log message that `291,723 SNPs are non-biallelic. These will be removed.`, which appears in both tests.

e.g. 
- When `allele_flip_check = TRUE`, the log message is `291,723 SNPs are non-biallelic. These will be removed.`, and there is indeed 291,723 variants in`snp_bi_allelic.tsv` 
- When `allele_flip_check = False`, the log message is still `291,723 SNPs are non-biallelic. These will be removed.`, but there are 1,037,559 variants in`snp_bi_allelic.tsv` 
- In both cases I still can't see the missing variants as aforementioned.

Finally I just wanted to mention that the reason to read in the VCF and convert to TSV in the first place is because I don't have a `bgi` index for the `VCF`.  I know this can be generated by other software, but my project includes using over 300 of the `VCF` files in the exact same format ([nightingale datasets](https://gwas.mrcieu.ac.uk/datasets/?gwas_id__icontains=met-d)), and so it adds on a pretty lengthy step to an already time-consuming workflow.

It's not all bad news, however!

### Current Solution

I _have_ however found a solution that works best for the current predicament, and it appears to resolve the initial issue.  That is:

1. Read in the VCF
2. Convert to data frame (and imputing the P-value)
3. Rather than remove all `ID`'s, I just remove the ~600,000 rows that do not have any `ID` value.
4. Munge the resulting dataset without wanting to infer the `rsID` with MSS (because they are already there, of course).

This way, I am certain that there are no indels being assigned to the incorrect ID, and actually it leads to the indels being recognised as present in the first place, which didn't seem to be the case as reported when opening this issue:

```
root@732a3c462216:/workspace/testing/issue/DROP_NA# cat met-d-L_VLDL_P_log_msg.txt
Standardising column headers.
First line of summary statistics file:
chr	POS	ALT	REF	ES	SE	AF	ID	P
Summary statistics report:
   - 11,624,626 rows
   - 11,602,288 unique variants
   - 13,228 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Checking for multi-GWAS.
Checking for multiple RSIDs on one row.
Checking SNP RSIDs.
Checking for merged allele column.
Checking A1 is uppercase
Checking A2 is uppercase
Ensuring all SNPs are on the reference genome.
Loading SNPlocs data.
Loading reference genome data.
Preprocessing RSIDs.
Validating RSIDs of 11,602,288 SNPs using BSgenome::snpsById...
BSgenome::snpsById done in 55 seconds.
Found 692,479 Indels. These won't be checked against the reference genome as it does not contain Indels.
WARNING If your sumstat doesn't contain Indels, set the indel param to FALSE & rerun MungeSumstats::format_sumstats()
Reordering so first three column headers are SNP, CHR and BP in this order.
Reordering so the fourth and fifth columns are A1 and A2.
Checking for missing data.
Checking for duplicate columns.
Checking for duplicate SNPs from SNP ID.
22,338 RSIDs are duplicated in the sumstats file. These duplicates will be removed
Writing in tabular format ==> /workspace/testing/issue/DROP_NA/dup_snp_id.tsv
Checking for SNPs with duplicated base-pair positions.
Found  Indels. These won't be checked for duplicates based on base-pair position as there can be multiples.
WARNING If your sumstat doesn't contain Indels, set the indel param to FALSE & rerun MungeSumstats::format_sumstats()
Checking for duplicated rows.
INFO column not available. Skipping INFO score filtering step.
Filtering SNPs, ensuring SE>0.
Ensuring all SNPs have N<5 std dev above mean.
Removing 'chr' prefix from CHR.
Making X/Y/MT CHR uppercase.
Checking for bi-allelic SNPs.
291,514 SNPs are non-biallelic. These will be removed.
Writing in tabular format ==> /workspace/testing/issue/DROP_NA/snp_bi_allelic.tsv
Warning: When method is an integer, must be >0.
1,619,992 SNPs (15.3%) have FRQ values > 0.5. Conventionally the FRQ column is intended to show the minor/effect allele frequency.
The FRQ column was mapped from one of the following from the inputted  summary statistics file:
FRQ, EAF, FREQUENCY, FRQ_U, F_U, MAF, FREQ, FREQ_TESTED_ALLELE, FRQ_TESTED_ALLELE, FREQ_EFFECT_ALLELE, FRQ_EFFECT_ALLELE, EFFECT_ALLELE_FREQUENCY, EFFECT_ALLELE_FREQ, EFFECT_ALLELE_FRQ, A1FREQ, A1FRQ, A2FREQ, A2FRQ, ALLELE_FREQUENCY, ALLELE_FREQ, ALLELE_FRQ, AF, MINOR_AF, EFFECT_AF, A2_AF, EFF_AF, ALT_AF, ALTERNATIVE_AF, INC_AF, A_2_AF, TESTED_AF, AF1, ALLELEFREQ, ALT_FREQ, EAF_HRC, EFFECTALLELEFREQ, FREQ.A1.1000G.EUR, FREQ.A1.ESP.EUR, FREQ.ALLELE1.HAPMAPCEU, FREQ.B, FREQ1, FREQ1.HAPMAP, FREQ_EUROPEAN_1000GENOMES, FREQ_HAPMAP, FREQ_TESTED_ALLELE_IN_HRS, FRQ_A1, FRQ_U_113154, FRQ_U_31358, FRQ_U_344901, FRQ_U_43456, POOLED_ALT_AF, AF_ALT, AF.ALT, AF-ALT, ALT.AF, ALT-AF, A2.AF, A2-AF, AF.EFF, AF_EFF, AF_EFF
As frq_is_maf=TRUE, the FRQ column will not be renamed. If the FRQ values were intended to represent major allele frequency,
set frq_is_maf=FALSE to rename the column as MAJOR_ALLELE_FRQ and differentiate it from minor/effect allele frequency.
Sorting coordinates.
Writing in tabular format ==> /workspace/testing/issue/DROP_NA/met-d-L_VLDL_P.LOG.munged.tsv
Summary statistics report:
   - 10,564,945 rows (90.9% of original 11,624,626 rows)
   - 10,564,945 unique variants
   - 10,500 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Done munging in 6.973 minutes.
```

In the above log, the following stands out compared to the original munging that lead to this issue:

1. `Found 692,479 Indels.` rather than `Found  Indels.` (btw I think this log is a bit confusing, it wasn't obvious to me that this message should have also had the # of indels)
2. `Validating RSIDs of 11,602,288 SNPs using BSgenome::snpsById...`, so in this case MSS attempts to validates ALL of the `11,602,288 unique variants`, and we don't anymore have the issue where we aren't sure why the million-odd SNPs weren't being validated initially! 

I think central to this entire issue is how MSS deals with indels and duplicates.  Although it would increase run-time, I think it would be necessary to perform a few additional condition checks for variants to meet before deciding to remove them as duplicates, or before inferring the `rsID` based on `CHR` and `BP`.  The most alarming thing is that `rsID`'s of the indels were inferred incorrectly.  I'm guessing MSS checks not only the `CHR` and `BP`, but then also checks to see if **one** of the alleles match the reference.  I understand that it's not possible to validated **both** the REF and ALT allele, since the ALT allele can be any of the four nucleotide bases even if the reference only 

I also thought it's worth mentioning now another issue I have identified from this investigation which has led to a doubt over the use of the `allele_flip_check` flag.  The *current solution* above is actually with `allele_flip_check = FALSE`, so in the end I'm using MSS for cleaning (i.e. remove duplicates) and converting to `TSV` predominantly.  I'll create a separate issue for that!


>From this you should be able to see where they are dropped and if you let me know the filtering step I can add the necessary log message.

As mentioned, I think the issue isn't with the dataset in the end, but rather the order of processes in MSS.  But for good measure, the following information is from using the `log_folder_ind` flag:

```
Number_of_variants   Log_ind_file
 0                            snp_not_found_from_chr_bp_2.tsv
 1332907               snp_not_found_from_chr_bp.tsv
 291664                 snp_bi_allelic.tsv
 21663                    dup_snp_id.tsvs
```

**Comment by Al-Murphy** [comment]
>What situations may these be? I have tried to be thorough with reading the docs, but I may have missed this! It has come to my attention that indels may need to be handled a bit differently than they are currently.
Basically the reference dataset we use in MSS (dbSNP) does not include indels so any checks like is the SNP on the reference genome, attempts to impute any missing data for indels or check the direction of the effect columns can not be done. True I could make this more clear so I've added this information to the vignette and will be available in the next release of MSS.

>We have a raw dataset that contains the following variants

Firstly, I agree how MSS deletes two of the three rows is not very intelligent and I have changed the code as follows:
1. I have added a `drop_indels` parameter so the user can fully remove indels to avoid this issue. By default this doesn't happen however.
2. The dropping was being done in the drop based on SNP ID check which didn't remove indels from the check although I was doing this for the drop based on base-pair position check. This was an error on my part and I have now added it in.

This results in the following:

```
chr	POS	ALT	REF	ES	SE	AF	P
8	134625772	GCCGAAGGAGA	G	9.74121e-4	0.00753359	0.081771	0.86000009654862275
8	134625772	A	G	0.0032263	0.0115306	0.039537	0.9899999895196127
8	134625772	GCCGAAGGAGA	G	6.41437e-4	0.00763662	0.080264	0.8200000899052511
#saved to a csv

#Running with MSS
ss <- data.table::fread("~/Downloads/example_ss.csv")

#drop indels
MungeSumstats::format_sumstats(ss,ref_genome = 'GRCh37',drop_indels = TRUE)
#result:
#Reading header.
#          SNP CHR        BP A1 A2      BETA        SE      FRQ    P
#1: rs539065912   8 134625772  G  A 0.0032263 0.0115306 0.039537 0.99

#keep indels
MungeSumstats::format_sumstats(ss,ref_genome = 'GRCh37')
#One of the indels dropped since the A1 and A2, BP and SNP cols all match
#result:
#Reading header.
#           SNP CHR        BP A1          A2      BETA         SE      FRQ         P
#1: rs539065912   8 134625772  G           A 0.0032263 0.01153060 0.039537 0.9900000
#2: rs539065912   8 134625772  G GCCGAAGGAGA 0.0009740 0.00753359 0.081771 0.8600001

#rerun with different A2 values
ss2 <- copy(ss)
ss2[3,ALT:='GC']

MungeSumstats::format_sumstats(ss2,ref_genome = 'GRCh37')
#both now kept
#result:
#Reading header.
#           SNP CHR        BP A1          A2      BETA         SE      FRQ         P
#1: rs539065912   8 134625772  G           A 0.0032263 0.01153060 0.039537 0.9900000
#2: rs539065912   8 134625772  G          GC 0.0006410 0.00763662 0.080264 0.8200001
#3: rs539065912   8 134625772  G GCCGAAGGAGA 0.0009740 0.00753359 0.081771 0.8600001
```
Note this functionality will be available in v 1.7.13.

>However, to make matters worse, the SNPs that relate to the two indels (first and third row) in actual fact belong to an [entirely different rsID](https://www.ncbi.nlm.nih.gov/snp/?term=rs113855465) rs113855465, which means that the decision to infer the rsID of all three variants based on CHR and BP ultimately dirties the resulting dataset. This is dangerous as without taking a very meticulous approach in validating the resulting munged data, it would not have come to my attention. In the above case, there is no situation where we would want to keep the indel SNP over the single-allele SNP, and we certainly wouldn't want to (incorrectly) infer the rsID of the indel to be that of the single-allele SNP.

I'm not entirely sure you are correct here, looking at the link you sent, the position given for grch37 is 8:134625773 whereas in your dataset you have 8:134625772. When you run MSS with this updated, these two are removed:
```
ss3 <- copy(ss)

ss3[3,POS:=134625773]
ss3[1,POS:=134625773]
MungeSumstats::format_sumstats(ss3,ref_genome = 'GRCh37')
#Reading header.
#           SNP CHR        BP A1 A2      BETA        SE      FRQ    P
#1: rs539065912   8 134625772  G  A 0.0032263 0.0115306 0.039537 0.99
```

Also note that the print out:

```
There is no SNP column found within the data. It must be inferred from other column information.
Found 2 Indels. These won't be checked against the reference genome as it does not contain Indels.
WARNING If your sumstat doesn't contain Indels, set the indel param to FALSE & rerun MungeSumstats::format_sumstats()
``` 
So what's happening here is that the indels are removed and not checked against the reference dataset, they only get kept when the original datset is used `ss` since the dbSNP dataset we use as reference identifies RS ID fro BP and CHR not A1/A2 so it is expected behaviour. When you put in the correct BP value, the two indels will be removed.

>To provide some additional context, the true raw dataset that I used for this situation is a VCF file downloaded from https://gwas.mrcieu.ac.uk/ - specifically [this file](https://gwas.mrcieu.ac.uk/datasets/met-d-L_VLDL_P/). The data in this format actually has rsID's for most of the variants already, which is how I know that the indels in the above example have their own rsID of rs113855465.

MSS can handle VCFs well so I would just input it raw. Better to pass in the incomplete RS ID column than no column.

>The raw dataset has almost 600,000 rows with rsID missing. So the way I was hoping to deal with this was to read in the vcf file using readr::read_tsv(), manually impute the P values as MSS expects (as it doesn't calculate P-values if -logP exists instead), and remove the ID column so that ALL of the variants have their rsID's inferred using MSS. The resulting data frame after reading in this VCF and before munging is the one that you can see in the first code block of this reply.

If you pass in the raw VCF MSS will convert the log p-val to a normal p-value and will also try and impute the missing RS IDs. It does this by a row basis so will try to do so for the 600k missing them. This is unnecessary.

>That is, the SNPs (at least the dozen or so that I checked) that have NA values in the ID column pre-munging are missing entirely from any of the resulting log or munge files. It is not clear where or why they are dropped. I also don't think that they are internally removed in their entirety because the number of resulting unique variants written to the munged file are a bit more than when I would manually remove all of these ~600,000 (591,593 to be exact) rows prior to munging (the results for which I describe in my [current solution](https://github.com/neurogenomics/MungeSumstats/issues/139#current-solution).

I think these are being dropped since an RS ID for them can't be found in the reference dataset. This is a separate issue now though to what you describe with indels so would you mind creating a new issue for this and giving a small example dataset so I can test where they are being dropped and add sufficient messaging (and logging of the dropped data if not already done so) to MSS?

**Comment by jksull** [comment]
Thanks for the detailed response!

>I have added a drop_indels parameter so the user can fully remove indels to avoid this issue. By default this doesn't happen however.

Thanks for this, I think it is a good idea.



> I'm not entirely sure you are correct here, looking at the link you sent, the position given for grch37 is 8:134625773 whereas in your dataset you have 8:134625772. When you run MSS with this updated, these two are removed:

I completely agree that the _true_ position according to the GRCh37 reference for these indel SNPs are actually `134625773`, however the `VCF` file itself has these as `134625772`, for whatever reason.  In practice I can't manually change these as you have done unfortunately. Please grep these rsID's in the [full file](https://gwas.mrcieu.ac.uk/datasets/met-d-L_VLDL_P/) to confirm that yourself if you are doubtful.

>MSS can handle VCFs well so I would just input it raw. Better to pass in the incomplete RS ID column than no column.

Could I please ask what the best way to pass the _raw_ VCF file to `MungeSumstats::format_sumstats()` is?

When I pass the filepath to `MungeSumstats::format_sumstats(path="/<pathto>/met-d-L_VLDL_P.vcf")`_nothing_ happens.  No error or logs appear, it just goes straight to a new`>` in the console (I'm sorry, I don't know how to explain this properly).

e.g.

```
>MungeSumstats::format_sumstats(
path="/<pathto>/met-d-L_VLDL_P.vcf",
...)

>
```

**Comment by Al-Murphy** [comment]
Cool, glad that fix helps!

Not sure what went wrong with the VCF you ahve, could be a corrupted download? But there is an easier way anyway, you can import directly from IEU GWAS with MSS:

```
vcf_ss <-MungeSumstats::import_sumstats('met-d-L_VLDL_P',
                                        nThread = 8)
```

Some of the output is:
```
Processing 1 datasets from Open GWAS.

========== Processing dataset : met-d-L_VLDL_P ==========

Using previously downloaded VCF.
Formatted summary statistics will be saved to ==>  /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T//RtmpN8fRPV/met-d-L_VLDL_P/met-d-L_VLDL_P.tsv.gz
Using local VCF.
File already tabix-indexed.
Finding empty VCF columns based on first 10,000 rows.
Dropping 1 duplicate column(s).
1 sample detected: met-d-L_VLDL_P
Constructing ScanVcfParam object.
VCF contains: 12,321,875 variant(s) x 1 sample(s)
Reading VCF file: multi-threaded (8 threads)
......
Renaming ID as SNP.
VCF file has -log10 P-values; these will be converted to unadjusted p-values in the 'P' column.
No INFO (SI) column detected.
Standardising column headers.
First line of summary statistics file: 
SNP	chr	BP	end	REF	ALT	FILTER	AF	ES	LP	SE	P	
Summary statistics report:
   - 12,216,212 rows
   - 12,195,120 unique variants
   - 13,930 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
......
Writing in tabular format ==> /var/folders/hd/jm8lzp7s4dl_wlkykzhz66x80000gn/T//RtmpN8fRPV/met-d-L_VLDL_P/met-d-L_VLDL_P.tsv.gz
Summary statistics report:                                                                                                           
   - 6,307,087 rows (51.6% of original 12,216,212 rows)
   - 6,307,087 unique variants
   - 5,507 genome-wide significant variants (P<5e-8)
   - 22 chromosomes
Done munging in 29.784 minutes.
Successfully finished preparing sumstats file, preview:
Reading header.
           SNP CHR    BP A1 A2   END FILTER      FRQ        BETA       LP         SE         P
1: rs544419019   1 11012  C  G 11012   PASS 0.086792 -0.00254505 0.050610 0.01016440 0.8900000
2: rs540538026   1 13110  G  A 13110   PASS 0.058576  0.00743138 0.301030 0.01355040 0.5000000
3:  rs62028691   1 13118  A  G 13118   PASS 0.189152  0.00463301 0.221849 0.00801853 0.5999997
4: rs546169444   1 14464  A  T 14464   PASS 0.157175 -0.00434060 0.387216 0.00850892 0.4100001
Returning path to saved data.

met-d-L_VLDL_P : Done in 29.797 minutes.
```

See the documentation on using IEU GWAS here:
https://neurogenomics.github.io/MungeSumstats/articles/OpenGWAS.html

**Comment by Al-Murphy** [comment]
I believe this will sort your issue but do reopen if not.

Cheers,
Alan.
