### ISSUE TITLE
Non-European populations

### ISSUE THREAD

**Issue by irisjansen** [neurogenomics/MungeSumstats#143]
Hi!

Thank you for this great R package, it really is of great value. One aspect that I am missing (or what I am not understanding correctly) is to munge sumstats of non-European populations.  So it would be possible to do the same allele frequency checks as for the European populations. Could I already accomplish this by setting a certain option? Or maybe it is something that you are planning to implement?

Thank you in advance!

Best wishes,
Iris

**Comment by irisjansen** [comment]
Hi Alan,

Thank you for your fast reply, and yes this definitely helps!

Best, 
Iris

**Comment by Al-Murphy** [comment]
Great! Feel free to reopen this issue if you have any further questions on it.

Thanks,
Alan.
