### ISSUE TITLE
Error: 'formatted_example' is not an exported object from 'namespace:MungeSumstats'

### ISSUE THREAD

**Issue by chenyangjjj** [neurogenomics/MungeSumstats#147]
Hi Alan,

When I ran the code `sumstats_dt <- MungeSumstats::formatted_example()`. I got the error report: Error: 'formatted_example' is not an exported object from 'namespace:MungeSumstats' How to solve it?

Also thanks for providing this great package. It is very helpful.

**Comment by Al-Murphy** [comment]
Hey! I would think this is a version issue, some of the older versions of MSS didn't have this fucntionality added. Please update to at least the latest release version of MSS available through bioconductor 3.16 (v1.6.0 or greater)

**Comment by chenyangjjj** [comment]
Thanks for the reply, It is! I works after I updated my bioconductor.
