### ISSUE TITLE
Add function to infer MAF

### ISSUE THREAD

**Issue by Al-Murphy** [neurogenomics/MungeSumstats#2]
May be useful to infer MAF although the downside is this wouldn't be related to the population in question so could result in questionable results. Similar code is here, taking MAF from UK Biobank: https://github.com/RajLabMSSM/echolocatoR/blob/dev/R/UKBiobank_LD.R
function located here: https://github.com/RajLabMSSM/echolocatoR/blob/6b9086d6755be0cc802027b76fb8314058fa0bf1/R/standardize.R#L304

**Comment by bschilder** [comment]
After discussing this with @Al-Murphy, we've decided it's beyond the scope of `MungeSumstats` to handle this. Inferring the right population/subpopulation is a very case-by-case task and will depend on the objectives of the user. Ideally, MAF should be inferred from the same sample that the GWAS was conducted in, but this information if not always possible to obtain, further complicating this situation.
