### ISSUE TITLE
Miscellaneous errors encountered when parsing summary stats

### ISSUE THREAD

**Issue by demodw** [neurogenomics/MungeSumstats#48]
Hi,

Thanks for this great tool. It really eases what I've been doing somewhat manually over the last year. 

I've ran into some issues which may be of interest to the general community, when trying to parse summary stats from the wild:

1. BOLT-LMM outputs files with headers A0/A1. This is not contained in the sumstatsColHeaders. There's also the additional issue that A1 is no longer the effect allele
2. SNP columns of the format chr:bp:a1:a2 fails to parse. Whenever it's present in the data I just get a `Error in .new_IRanges_from_start_end(start, end) 'start' or 'end' cannot contain NAs`. Setting the value to missing for these entries fixes the problem
3. Lower case alleles are not automatically converted to upper case
4. Entries with missing CHR/BP are not automatically removed and instead results in an error
5. Entries with multiple RSIDs seperated by a comma (e.g. rs1,rs2) leads to an error. The current code seems to only catch rs1_rs2.

On a minor note, it would also be nice if it was possible to feed the main function, format_sumstats, a data.frame with sumstats directly, to avoid loading the data a second time if any manipulation is needed.

**Comment by Al-Murphy** [comment]
Hey David,

I'm glad to hear that the package has helped, we developed MungeSumstats to make these manual jobs easier! The amount of variation in summary statistics files never ceases to amaze me! I'll try incorporate some of these changes over the next few days as I don't think they will be too much work. 

Thanks for your suggestions,
Alan.

**Comment by Al-Murphy** [comment]
2. Can you give a small subset which gives the same error for me to test? MungeSumstats should be able to handle chr:bp:a1:a2 so I'm guessing a row is missing some data from the columns.
3. Lower case alleles not converted - do you mean a,c,t,g -> A,C,T,G?
4. Entries with missing CHR/BP should be removed, I have checks for that. Could you send a small sample dataset where this is an issue?

**Comment by Al-Murphy** [comment]
I have made some of the changes which are now available in the master branch:

1. On the A0/A1 case. From the [BOLT-LMM manual](https://cdn1.sph.harvard.edu/wp-content/uploads/sites/181/2014/11/BOLT-LMM_v1.2_manual.pdf):
    - ALLELE1: first allele in bim file (usually the minor allele), used as the effect allele
    - ALLELE0: second allele in bim file, used as the reference allele
 So I have made the mapping file so all variation of spellings of A0/A1 go to ref/alt whereas A1/A2 will still go to ref/alt. 
 Again the fact that people have chosen A1 to mean the exact opposite thing in these two outputs highlights a big issue in the field! 

5. I have updated `check_multi_rs_snp` so it can now handle all punctuation with/without spaces. So if a row contains `rs1234,rs5678` or `rs1234, rs5678` or any other punctuation character other than `,` these can be handled. Use `remove_multi_rs_snp` input parameter to control whether these are removed or the first RS ID taken.

- Minor note: `MungeSumstats:format_sumstats(path)` can now also take a data.frame or data.table sumstats input.

**Comment by demodw** [comment]
Thanks for the updates!

Here's some example of summary data that still fails (sorry about the screenshots, I'm working in a secure environment so I can't copy text out):

https://www.nature.com/articles/s41467-020-19742-5#data-availability (http://www.geenivaramu.ee/tools/misc_sumstats.zip). This is the output format METAL uses.. I think there's an issue with splitting MarkerName into CHR and BP. 
![image](https://user-images.githubusercontent.com/5146736/130768374-58effbff-05f6-4a6b-976b-21539ffa1350.png)

https://pubmed.ncbi.nlm.nih.gov/30239722/ (https://zenodo.org/record/1251813/files/bmi.giant-ukbb.meta-analysis.females.23May2018.txt.gz?download=1). It might be the rsid:A1:A2 notation that causes a problem?
![image](https://user-images.githubusercontent.com/5146736/130769873-f27a5295-e0d3-424a-914b-20505df9ea98.png)

https://www.nature.com/articles/s41467-019-12536-4 (ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST009001-GCST010000/GCST009157). Again I think it's the combination of a column with RSIDs and chr:bp. 
![image](https://user-images.githubusercontent.com/5146736/130771289-cae33c4e-62bf-447b-a7b7-d1bfdb308312.png)

For reference, I'm currently using v1.1.15.

**Comment by demodw** [comment]
Cheers, looks like this solved the issues. Thanks!

David
