### ISSUE TITLE
Provide liftover to other genome builds

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MungeSumstats#50]
Currently, `MungeSumstats` detects the current genome build but does not do liftover to one genome build or another. Would be awesome to implement this.

I extracted the functions needed to do this from [XGR](https://xgr.r-forge.r-project.org/), since XGR can be a bit tricky to install and this is the only part I needed for liftover.

https://github.com/RajLabMSSM/echolocatoR/blob/master/R/xLiftOver.R

**Comment by Al-Murphy** [comment]
Might be a 'nicer' solution to got with a Bioconductor version of a liftover package: https://www.bioconductor.org/packages/release/workflows/html/liftOver.html it requires GRanges but if we do this as the last step before saving/outputting and not do it by default should be okay

**Comment by bschilder** [comment]
that sounds good too! should be easy enough to convert with `MungeSumstats::to_GRanges`

**Comment by bschilder** [comment]
Implemented a bioc-based version of this in echoLD with these two functions:
https://github.com/RajLabMSSM/echoLD/blob/main/R/liftover.R
https://github.com/RajLabMSSM/echoLD/blob/main/R/get_chain_file.R

They seems to be working pretty well. Feel free to copy these over to `MungeSumstats`, or I can if you prefer.

**Comment by Al-Murphy** [comment]
Great, be brilliant good to use that here too then!

I don' think I'll have time to get to this in the near future just to let you know in case you need it for some work you're doing.

**Comment by Al-Murphy** [comment]
This has been implemented in 1.1.19
