### ISSUE TITLE
error in get_chian_file.R 

### ISSUE THREAD

**Issue by Cloufield** [neurogenomics/MungeSumstats#84]
Hi, thanks a lot for your wonderful package.  It really is an efficient tool.
I am just wondering if you could kindly provide an option to directly use local chain files? 

When I try to liftover my sumstats, there was an error like (sorry I forgot to keep the original log)
```
grepl("Couldn't connect to server",error_dwnld$message) 
$ operator is invalid for atomic vectors
```

it seems that this error comes from this part in get_chian_file.R:
```
        if(is(error_dwnld,"warning")||is(error_dwnld,"error")||
           grepl("Couldn't connect to server",error_dwnld$message)||
            grepl("Couldn't resolve host name",error_dwnld$message)
            )
```
After I deleted this part in the source code, reinstalled and just used the local chain file, it works well.

**Comment by Al-Murphy** [comment]
Hey Cloufield! 

Glad to hear the package is useful for you. I'm trying to understand the error as it isn't something I've come across in my testing (on any operating system). It would be great if you could send a small sample sumstats that gives the same error? The error message you say was likely printed occurs when there is no internet access, could this be the issue you're having?

Is the only reason you supplied your own chain file because of the error? If that is the case, I would prefer to sort the issue rather than giving the user the option to input their own chan file. Currently, Mungesumstats works out the chain file from the reference genome which can be inferred from the data or is inputted by the user. Therefore, if we allow a user to also supply a chain file there could be a mismatch which would give strange results and be quite hard to debug.

Thanks,
Alan.

**Comment by Cloufield** [comment]
Thanks for your reply. 

I tried to replicate the error using 10 rows. 
Internet connection: one of the fastest in Japan, I believe this should not be the problem.  
My Linux server:  CentOS Linux release 7.8.2003 (Core)  

I installed MungeSumstats using bioconductor follwing instruction on https://neurogenomics.github.io/MungeSumstats/articles/MungeSumstats.html

And by using local chain I mean to skip downloading from UCSC and directly use the snapshot chain file that comes when you insall the package (maybe adding a simple option like `local_chain=TRUE` will do).

Here is the log:
```
Standardising column headers.

First line of summary statistics file: 

MARKERNAME	CHROMOSOME	POSITION	NEA	EA	P	BETA	SE	EAF	N	OR	OR_95L	OR_95U	

Summary statistics report:
   - 9 rows
   - 9 unique variants
   - 0 genome-wide significant variants (P<5e-8)
   - 1 chromosomes

Checking for multi-GWAS.

Checking for multiple RSIDs on one row.

Checking SNP RSIDs.

Checking for merged allele column.

Ensuring all SNPs are on the reference genome.

Loading reference genome data.

8 SNPs are not on the reference genome. These will be corrected from the reference genome.

Checking for correct direction of A1 (reference) and A2 (alternative allele).

Checking for missing data.

Checking for duplicate columns.

Checking for duplicate SNPs from SNP ID.

Checking for SNPs with duplicated base-pair positions.

Filtering SNPs, ensuring SE>0.

Ensuring all SNPs have N<5 std dev above mean.

Removing 'chr' prefix from CHR.

Making X/Y CHR uppercase.

Checking for bi-allelic SNPs.

N already exists within sumstats_dt.

Performing data liftover from GRCh38 to GRCh37.

Downloading chain file from UCSC Genome Browser.

Error: $ operator is invalid for atomic vectors
Traceback:

1. MungeSumstats::format_sumstats(path = sumstats, ref_genome = "GRCh38", 
 .     convert_ref_genome = "GRCh37", convert_small_p = TRUE, compute_z = FALSE, 
 .     force_new_z = FALSE, compute_n = 0L, convert_n_int = TRUE, 
 .     analysis_trait = NULL, INFO_filter = 0.3, FRQ_filter = 0, 
 .     pos_se = TRUE, effect_columns_nonzero = FALSE, N_std = 5, 
 .     N_dropNA = TRUE, rmv_chr = c("X", "Y", "MT"), rmv_chrPrefix = TRUE, 
 .     on_ref_genome = TRUE, strand_ambig_filter = FALSE, allele_flip_check = TRUE, 
 .     allele_flip_drop = TRUE, allele_flip_z = TRUE, allele_flip_frq = TRUE, 
 .     bi_allelic_filter = TRUE, snp_ids_are_rs_ids = TRUE, remove_multi_rs_snp = FALSE, 
 .     frq_is_maf = TRUE, sort_coordinates = TRUE, nThread = 1, 
 .     save_path = save_path, write_vcf = FALSE, tabix_index = FALSE, 
 .     return_data = FALSE, return_format = "data.table", ldsc_format = FALSE, 
 .     log_folder_ind = FALSE, log_mungesumstats_msgs = FALSE, log_folder = out_path, 
 .     imputation_ind = FALSE, force_new = FALSE, mapping_file = sumstatsColHeaders)
2. liftover(sumstats_dt = sumstats_return$sumstats_dt, convert_ref_genome = convert_ref_genome, 
 .     ref_genome = ref_genome, imputation_ind = imputation_ind)
3. get_chain_file(build_conversion = build_conversion, ucsc_ref = ucsc_ref, 
 .     verbose = verbose)
4. grepl("Couldn't connect to server", error_dwnld$message)
5. is.factor(x)

```

A sample of sumstats:
```
MARKERNAME	CHROMOSOME	POSITION	NEA	EA	P	BETA	SE    EAF	N	OR	OR_95L	OR_95U
rs1274919517	1	108391	A	G	0.424	0.20552	0.2573	0.00221	2306351.2281635439871177	0.7417235100504539	2.033622597019195
rs74337086	1	115637	G	A	0.424	0.20552	0.2573	0.00221	2306351.2281635439871177	0.7417235100504539	2.033622597019195
rs1292537993	1	137928	G	A	0.424	0.20552	0.2573	0.00221	2306351.2281635439871177	0.7417235100504539	2.033622597019195
rs1264891165	1	184280	C	T	0.424	0.20552	0.2573	0.00221	2306351.2281635439871177	0.7417235100504539	2.033622597019195
rs1179030655	1	502543	G	C	0.424	0.20552	0.2573	0.00221	2306351.2281635439871177	0.7417235100504539	2.033622597019195
rs1223421187	1	588427	G	C	0.424	0.20552	0.2573	0.00221	2306351.2281635439871177	0.7417235100504539	2.033622597019195
rs28760963	1	591353	C	T	0.424	0.20552	0.2573	0.00221	2306351.2281635439871177	0.7417235100504539	2.033622597019195
rs76388980	1	593262	G	A	0.424	0.20552	0.2573	0.00221	2306351.2281635439871177	0.7417235100504539	2.033622597019195
rs1350728974	1	605289	C	A	0.424	0.20552	0.2573	0.00221	2306351.2281635439871177	0.7417235100504539	2.033622597019195
```

BTW, some case-control gwas sumstats provide only OR, OR_95L, OR_95U instead of beta/se... currently MungeSumstats only convert OR.

**Comment by Al-Murphy** [comment]
Okay I can't seem to replicate the error but it appears to me that the download of the chain file is failing due to the server being down - I guess just in the East since I have no issue here in the UK. This shouldn't throw an error though since MungeSumstats is designed to use the local version if this happens. What version of MungeSumstats do you get if you run:

```
packageVersion("MungeSumstats")
```

**Comment by Al-Murphy** [comment]
Apologies I can actually get the same error - as mentioned MungeSumstats should use the local file if the download of the chain file fails. This doesn't appear to be working. I'll get a fix implemented today and will update you when it's done

**Comment by Al-Murphy** [comment]
I have no pushed a fix for this issue, this will take a few days to update on bioconductor (using MungeSumstats through `biocManager::install("MungeSumstats")`: the release version) but feel free to install directly from github as the fix is implemented there too.

Thanks for pointing this out!

**Comment by Cloufield** [comment]
Thanks a lot for the fix. Really appreciate it.
