### ISSUE TITLE
Odds ratio (OR) shouldn’t be negative value when flipping effect allele

### ISSUE THREAD

**Issue by Huifang-Xu** [neurogenomics/MungeSumstats#88]
Hi, I tried to munge a GWAS summary statistics that uses odds ratio (OR) to estimate effect. I found MungeSumstats incorrectly convert OR when flipping effect allele. After flipping effect allele, new OR should be positive, which should be 1/OR. But MungeSumstats outputes negative values. 
![image](https://user-images.githubusercontent.com/91753987/156465245-312d59a0-7f87-4075-97a3-d18f6bf8fb7b.png)

The code I used is as follows:
```
df <- format_sumstats(path=inFile,
                      ref_genome="GRCh37",
                      convert_small_p=TRUE,
                      allele_flip_check=TRUE,
                      allele_flip_drop=FALSE,
                      snp_ids_are_rs_ids=FALSE,
                      return_data=TRUE,
                      nThread=2,
                      log_mungesumstats_msgs=T,
                      log_folder=workDir
                      )
```

**Comment by Al-Murphy** [comment]
Hi Huifang,

Thanks for getting in touch! What version of MungeSumstats are you currently using? This was identified and a bug fix implemented (see commit bug fix: Correct flipping of OR). Can you ensure you update to the latest version of MungeSumstats either for the current release of devel bioconductor as both have had the fix implemented.

Let me know if this works

Thanks,
Alan.

**Comment by Huifang-Xu** [comment]
Hi Alan,

I downloaded (```git clone```) all R scripts from GitHub last month. Because when I use the R packages  MungeSumstats::format_sumstats(), I can't change the parameters. I don't think the R functions on GitHub has been updated, so I used the old version.

![image](https://user-images.githubusercontent.com/91753987/156836845-5cd6b6f8-0336-458a-b6ef-e5d8e85c6ec5.png)

Thanks,
Huifang

**Comment by Huifang-Xu** [comment]
Could you plsease tell me how to update the MungeSumstats R package to version 1.2.2? I found that MungeSumstats package installed last month is version 1.0.1. I just tried to reinstall MungeSumstats R package, but it is still version 1.0.1. Thank you!

![image](https://user-images.githubusercontent.com/91753987/156840440-e98f2f0a-5773-4977-a755-9719a1fa54f9.png)

**Comment by Al-Murphy** [comment]
This will get you the latest release version of MungeSumstats. In general, I would say avoid using the github version unless there is a specific feature there that isn't in the release version yet since it is viewed as the dev branch and may not be stable: 

```
BiocManager::install("MungeSumstats")
```
