### ISSUE TITLE
Cache liftover chain files

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/MungeSumstats#93]
Storing chain files to a package-specific cache means the user won't have to re-download the chain file each time.

```R
get_chain_file <- function( 
....
                           save_dir = tools::R_user_dir(package = "echotabix",
                                                        which = "cache"),
....
)
```

Might also be nice to export the `liftover` function since this could be generally useful.

I"ll make these changes at some point and push, if that's cool with you @Al-Murphy

**Comment by Al-Murphy** [comment]
More than happy for the liftover to be made external.

Just on the chain files, we have local versions in the package in case the user doesn't have internet access. Also the chain files are cached so only really need to download once (and this is fast - they are small) I like to keep this download in case the chain files are ever updated. If we moved to that method we would need to update with any changes. So overall I think the current method is probably okay but let me know if I'm missing something good about the alternative?

**Comment by bschilder** [comment]
Ohhh, i see. I was basing this off a (possibly old) version [I had adapted for `echotabix`](https://github.com/RajLabMSSM/echotabix/blob/main/R/get_chain_file.R). You're totally right, these are cached in a slightly different way. 


Will still do the export tho. Thanks!

**Comment by bschilder** [comment]
Done! Plus some upgrades/new params to the `liftover` function.
